### ISSUE TITLE
Led Shim + Kali Linux

### ISSUE THREAD

**Issue by bobster316** [pimoroni/led-shim#13]
I have some issues getting the led shim to work corretcly with Kali Linux, the example rainbow.py file
pattern is intermittentm not smooth as when ruinning Raspberry Pi OS.

To setup the Led shim on Kali Linux i folliowed the following web page
https://projectarc.co.uk/fingers-in-many-pis/pimoroni-led-shim-on-kali-linux

Is there any way to fix this?

Please see example of the issue in my youtube video
[https://youtu.be/7u3DQ6Wroig](url)

**Comment by Gadgetoid** [comment]
It could be i2c baudrate but we don't test outside the safe, warm bubble of Raspberry Pi OS.

Try adding `baudrate=400000` to the end of whatever line enables the i2c found wherever Kali keeps `config.txt`
