### ISSUE TITLE
Function reference link is broken  

### ISSUE THREAD

**Issue by alphanumeric007** [pimoroni/led-shim#2]
Clicking the Function reference - http://docs.pimoroni.com/ledshim/ link just gets me a 404 error. 
Add if I go to http://docs.pimoroni.com/ the LED Shim isn't in the list?

**Comment by Gadgetoid** [comment]
Ah- it would appear that the documentation generation hasn't been finished, and the docs generated, for LED shim yet. I've popped this on my TODO list.

**Comment by alphanumeric007** [comment]
Ok, thanks. I haven't bought one just yet, its on my wish list though. I was wanting to have a look at the function list to get an idea on how hard it will be to do what I want to do with it.

JFI I'm the alphanumeric from the Pimoroni forum ;) .

**Comment by alphanumeric007** [comment]
Just got my first LED Shim. Have you made any headway on adding the function list? Just friendly nudge. ;)
I think I can probably do it from the examples, it'll just take me a lot longer.

**Comment by Gadgetoid** [comment]
Better late than never- docs now exist at http://docs.pimoroni.com/ledshim/

Had some confusion between `led-shim` and `ledshim` in the URL!
