### ISSUE TITLE
Ledshim IOError

### ISSUE THREAD

**Issue by bking46** [pimoroni/led-shim#5]
Hi All,

Could you kindly help me out with the following error please? I've trying to run the examples but I am getting this error. I2c is enabled using raspi-config. The setup I have is a Raspberry Pi3 B+ attached to a Geekworm 3.5 inch 800x480 HD TFT LCD. I have tried to run the ledshim also without the display hat attached and the result is the same. Any support is much appreciated. Thanks

Error message in terminal shim lights don't light up:
pi@raspberrypi:~/Pimoroni/ledshim/examples $ ./test.py
Traceback (most recent call last):
  File "./test.py", line 10, in 
    ledshim.show()
  File "/usr/lib/python2.7/dist-packages/ledshim/is31fl3731.py", line 243, in show
    self.setup()
  File "/usr/lib/python2.7/dist-packages/ledshim/is31fl3731.py", line 86, in setup
    raise e
IOError: [Errno 2] No such file or directory

Make sure you've enabled i2c in your Raspberry Pi configuration.

pi@raspberrypi:~/Pimoroni/ledshim/examples $ 

pi@raspberrypi:~/Pimoroni/ledshim/examples $ ./test.py
Traceback (most recent call last):
  File "./test.py", line 10, in 
    ledshim.show()
  File "/usr/lib/python2.7/dist-packages/ledshim/is31fl3731.py", line 243, in show
    self.setup()
  File "/usr/lib/python2.7/dist-packages/ledshim/is31fl3731.py", line 86, in setup
    raise e
IOError: [Errno 2] No such file or directory

Make sure you've enabled i2c in your Raspberry Pi configuration.

**Comment by Gadgetoid** [comment]
It looks like the device node it's expecting for i2c is missing. What do you see if you run `ls /dev/i2c-*` and `i2cdetect -y 1`?

**Comment by bking46** [comment]
This can be closed, I had another ledshim and that is working on my setup. It seem my unit was defective, not software related. Thanks for getting back.

**Comment by Gadgetoid** [comment]
That's really strange, `IOError: [Errno 2] No such file or directory` happens due to a setup issue not a hardware fail. You'd get a different flavour of `IOErrror` for the latter.

Either way, I'm glad it works!

**Comment by bking46** [comment]
Unfortunately the error has started to appear with the board that was working previously. I don't understand what am I doing incorrectly. Haven't made any changes to the system. For reference I am attaching a screen shot with the error message and output from  ls /dev/i2c-* and i2cdetect -y 1
![Screenshot_20191204-232312_Mobile SSH](https://user-images.githubusercontent.com/58046919/70229153-5219ab00-175e-11ea-80f5-453726266d2d.jpg)

**Comment by Gadgetoid** [comment]
I'd guess it's a connection issue- the friction-fit headers aren't perfect and are very sensitive to pin thickness or any slight bends in the GPIO. One technique to check this is to wedge some folded cardboard between the two rows of GPIO pins once the LED SHIM is pushed down. This should splay the pins out slightly and make a better electrical connection.

Soldering a header to the SHIM or the SHIM to the Pi is a more drastic but permenant solution once you've confirmed it works at all.

**Comment by bking46** [comment]
Thanks so much, this fix worked. My ledshim is back in working order🙏
