### ISSUE TITLE
Should this line say "between 0 and 255"?

### ISSUE THREAD

**Issue by dannystaple** [pimoroni/led-shim#6]
The error message looks incorrect at:

https://github.com/pimoroni/led-shim/blob/1a44f11c28bfb44e8a8f6a56a0f405dc7f4927ec/library/ledshim/is31fl3731.py#L232

**Comment by Gadgetoid** [comment]
Yes. Yes it should. The line above is a dead giveaway 😆 Good spot, thank you!
