### ISSUE TITLE
LED SHIM not listed with other SHIMs in Pimoroni Dashboard

### ISSUE THREAD

**Issue by grndkntrl** [pimoroni/led-shim#8]
Hi,

Just a quick one; as per subject/title the LED SHIM isn't currently listed alongside the other SHIMs in the dashboard, nor alongside any of the other HATs, PHATs or other products.

I had just freshly installed the dashboard from the raspbian repo when I ran into this issue so not sure if it just hasn't made it into the current one or just never has been.

I've installed the library directly as per the _readme.md_ here, so not a big deal for me to get around, but I guess it's something that others will run into so hence opening this as an issue.

Cheers,
Glenn

![Screenshot from 2020-08-07 17-53-42](https://user-images.githubusercontent.com/5685696/89670085-82f74480-d8d8-11ea-9f79-b728fc61955d.png)
![Screenshot from 2020-08-07 17-55-31](https://user-images.githubusercontent.com/5685696/89670087-838fdb00-d8d8-11ea-9d9d-b11d494d5552.png)
![Screenshot from 2020-08-07 17-56-16](https://user-images.githubusercontent.com/5685696/89670088-84287180-d8d8-11ea-8958-76c4182de30e.png)
![Screenshot from 2020-08-07 17-56-59](https://user-images.githubusercontent.com/5685696/89670091-84c10800-d8d8-11ea-8d6f-56dbf65d9199.png)

**Comment by Gadgetoid** [comment]
I don't think the dashboard has been updated in a long, long time. No new products have been added since `button-shim` in Jun 2018 in fact! I've added LED Shim to the open issue for this. Thank you!
